version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    hostname: elasticsearch
    container_name: elasticsearch
    networks:
      - logmonnet
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.1.0
#    hostname: kibana-ui
#    container_name: kibana-ui
#    environment:
#      SERVER_NAME: kibana
#      ELASTICSEARCH_URL: http://elasticsearch:9200/
#      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
#    networks:
#      - logmonnet
#    ports:
#      - "5601:5601"
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch

networks:
  logmonnet:
    driver: "bridge"